### ISSUE TITLE
It doesn't work in Mojave Version

### ISSUE THREAD

**Issue by coooliang** [GWesley/GWNewFile#1]
It doesn't work in MacOS 10.14.3 Mojave System

**Comment by ShaoXinSen** [comment]
My MacOS 10.14.3 Mojave working well

**Comment by GWesley** [comment]
> It doesn't work in MacOS 10.14.3 Mojave System

If you can't find it, try this.
After build,  right click blank space in finder's toolbar, choose customize toolbar, find NewFile and drag it to the toolbar

![1552591244090](https://user-images.githubusercontent.com/2985638/54385679-9cf21080-466d-11e9-8b4b-cc423fce8c2f.jpg)

**Comment by coooliang** [comment]
@GWesley 
thx ，I found
